config/routes.rb
Bayesspam::Application.routes.draw do
  resources :messages

  get "classify/index"

  post "classify/predict"

  get "classify/result"

  get "message_stats/refresh"

  get "message_stats/show"

  root :to => 'classify#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  RELEVANT = 0
  SPAM = 1

  validates :content, :presence => true
  validates :status, :presence => true

  after_destroy do |message|
    logger.debug "Decreasing stats after destroy"
    MessageStats.decrement_stats(message)
  end
  
  after_save do |message|
    logger.debug "Increasing stats after save"
    MessageStats.increment_stats(message)
  end

  def status_str
    if status.eql?(RELEVANT)
      return "Relevant"
    elsif status.eql?(SPAM)
      return "Spam"
    else
      return "Invalid Status"
    end
  end
end

app/models/message_stats.rb
class MessageStats

  def self.stats
    stats = Rails.cache.fetch(:stats_store) { initialize_stats }
    return stats
  end

  def self.initialize_stats
    # "cat" is short for category
    # This classifier only has 2 categories - Relevant and Spam
    stats = {}

    stats[:word_total] = 0.0
    stats[:cat_totals] = {}
    stats[:cat_totals][:relevant] = 0.0
    stats[:cat_totals][:spam] = 0.0

    stats[:word_cat_totals] = {}
    stats[:word_cat_totals][:relevant] = Hash.new(0.0)
    stats[:word_cat_totals][:spam] = Hash.new(0.0)

    Message.find_each do |message|
      stats = self.compile_words(stats, message, 1)
    end

    return stats
  end

  def self.decrement_stats(message)
    self.update_stats(message, -1)
  end

  def self.increment_stats(message)
    self.update_stats(message, 1)
  end

  def self.refresh_stats
    Rails.cache.write(:stats_store, initialize_stats)
  end

  private
    def self.update_stats(message, multiplier)
      previous_stats = self.stats.dup

      stats = self.compile_words(previous_stats, message, multiplier)

      Rails.cache.write(:stats_store, stats)
    end

    def self.compile_words(stats, message, multiplier)
      if message.status_str.eql?("Relevant")
        status = :relevant
      else
        status = :spam
      end

      content = message.content.sub(/#java/, "")
      content = content.sub(/https{,1}:\/\/\S* /, "")

      msg_words = content.split(/\W/)

      msg_words.each do |word|
        stats[:word_total] = stats[:word_total] + (1.0 * multiplier)
        stats[:cat_totals][status] = stats[:cat_totals][status] + (1.0 * multiplier)
        stats[:word_cat_totals][status][word] = stats[:word_cat_totals][status][word] + (1.0 * multiplier)
      end

      return stats
    end

end # class MessageStats

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/classify_controller.rb
class ClassifyController < ApplicationController
  def index
  end

  def predict
    @content = Twitter.search("#java -rt", :rpp => 1, :lang => "en").first.text
    msg_words = @content.split(/\W/)
    
    stats = MessageStats.stats
    eps_prob = 1.0 / stats[:word_total]

    relevant_eps = 1.0
    spam_eps = 1.0

    relevant_counts = []
    spam_counts = []

    msg_words.each do |word|
      if (stats[:word_cat_totals][:relevant][word] == 0.0)
        relevant_eps *= eps_prob
      else
        relevant_counts.push(stats[:word_cat_totals][:relevant][word]) 
      end

      if (stats[:word_cat_totals][:spam][word] == 0.0)
        spam_eps *= eps_prob
      else
        spam_counts.push(stats[:word_cat_totals][:spam][word])
      end
    end

    post_relevant = (stats[:cat_totals][:relevant] / stats[:word_total])*(product(relevant_counts) / (stats[:cat_totals][:relevant] ** relevant_counts.length))*relevant_eps
    post_spam = (stats[:cat_totals][:spam] / stats[:word_total])*(product(spam_counts) / (stats[:cat_totals][:spam] ** spam_counts.length))*spam_eps

    logger.debug "Posterior Relevant: #{post_relevant}"
    logger.debug "Posterior Spam: #{post_spam}"

    if post_relevant > post_spam
      @prediction = "Relevant"
    else
      @prediction = "Spam"
    end

    render :action => "result"
  end

  def result
  end

  private
    def product(word_counts)
      product = 1.0
      word_counts.each { |count| product *= count }
      return product
    end
end

app/controllers/message_stats_controller.rb
class MessageStatsController < ApplicationController
  # GET /message_stats/refresh
  # This is a utility service for app administrators to refresh the stats cache if needed
  def refresh
    MessageStats.refresh_stats
    redirect_to "/"
  end

  #GET /message_stats/show
  def show
    @stats = MessageStats.stats
    respond_to do |format|
      format.html # show.html.erb
    end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.order("status, content").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    prev_message = Message.new
    prev_message.content = @message.content
    prev_message.status = @message.status

    respond_to do |format|
      if @message.update_attributes(params[:message])
        logger.debug "Removing previous message from stats"

        MessageStats.decrement_stats(prev_message)

        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classify_helper.rb
module ClassifyHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/classify/index.html.erb
<h1>spamster - a demonstration of a naive bayes spam filter</h1>

<p>
  Click the button below. spamster will use the training set data to determine if the tweet
  retrieved is spam or not.
</p>

<%= form_tag(:controller => "classify", :action => "predict") do %>
  <div class="actions">
    <%= submit_tag("Grab a #java tweet and predict!") %>
  </div>
<% end %>

<p>
  <%= link_to "View and Modify the Training Set", messages_path %>
</p>

app/views/classify/result.html.erb
<p>
  <b>Submitted Message</b>
</p>

<p>
  <%= @content %>
</p>

<p>
  Drumroll, please.........
</p>

<p>
  <b>Predicted Category:</b>
  <%= @prediction %>
</p>

<%= link_to 'Try Another Prediction', '/' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>spamster - a demonstration of a naive bayes spam filter</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/message_stats/show.html.erb
<h1>Training Set Statistics</h1>

<p>
  <b>Total Number of Words:</b>
  <%= @stats[:word_total] %>
</p>

<p>
  <b>Total Number of Relevant Words:</b>
  <%= @stats[:cat_totals][:relevant] %>
</p>

<p>
  <b>Total Number of Spam Words:</b>
  <%= @stats[:cat_totals][:spam] %>
</p>

<h2>Relevant Word Counts</h2>

<% @stats[:word_cat_totals][:relevant].each do |word, count| %>
<p>
  <b><%= word %>:</b>
  <%= count %>
</p>
<% end %>

<h2>Spam Word Counts</h2>

<% @stats[:word_cat_totals][:spam].each do |word, count| %>
<p>
  <b><%= word %>:</b>
  <%= count %>
</p>
<% end %>


<%= link_to 'Show Training Set', messages_path %>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label "Relevant" %>
    <%= f.radio_button :status, Message::RELEVANT, :checked => true %>
    <%= f.label "Spam" %>
    <%= f.radio_button :status, Message::SPAM %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.content %></td>
    <td><%= message.status_str %></td>
    <td><%= link_to 'Show', message %></td>
    <td><%= link_to 'Edit', edit_message_path(message) %></td>
    <td><%= link_to 'Destroy', message, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_message_path %> <br/>
<%= link_to 'Message Statistics', "message_stats/show" %> <br/>
<%= link_to 'Home', "/" %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @message.content %>
</p>

<p>
  <b>Status:</b>
  <%= @message.status_str %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %> <br/>